# Generated by Django 2.0.2 on 2018-08-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de creación'),
        ),
    ]
